package org.intellij.privacyhelper.codeInspection.utils;

import java.util.*;

/**
 * Created by tianshi on 12/27/17.
 */
public class Constants {
    public static final Map<String, String> SENSITIVE_FIELD_VALUES = Collections.unmodifiableMap(new HashMap<String, String>() {{
        put(String.format("LocationDataType.%s", fine_grained_latitude_longitude), "Is it okay to use coarse-grained location data instead? See more options in quickfix list");
        put(String.format("LocationPurpose.%s", purpose_location_data_collection_for_analytics), "Collecting location data for analytics may raise privacy concerns. To address this issue, please consider explaining how the data is collected and shared in your privacy policy or other privacy notices to your users");
        put(String.format("LocationPurpose.%s", purpose_location_data_collection_for_advertising), "Collecting location data for targeted advertising may raise privacy concerns. To address this issue, please consider explaining how the data is collected and shared in your privacy policy or other privacy notices to your users");
    }});
    public static final Map<String, String> DESCRIPTION_MAPPING = Collections.unmodifiableMap(new HashMap<String, String>() {{
        put(String.format("LocationDataType.%s", fine_grained_latitude_longitude),
                String.format("\"%s\": The best accuracy of location data in Android (accuracy: about 10 meters).",
                        fine_grained_latitude_longitude));
        put(String.format("LocationDataType.%s", coarse_grained_latitude_longitude),
                String.format("\"%s\": accuracy>100 meters.",
                        coarse_grained_latitude_longitude));
        put(String.format("LocationDataType.%s", block_level_latitude_longitude),
                String.format("\"%s\": accuracy about 100 meters.",
                        block_level_latitude_longitude));
        put(String.format("LocationDataType.%s", city_level_latitude_longitude),
                String.format("\"%s\": accuracy about 10km",
                        city_level_latitude_longitude));
        put(String.format("UIDType.%s", android_id),
                String.format("\"%s\": Android ID (SSAID)", android_id));
        put(String.format("UIDType.%s", advertising_id),
                String.format("\"%s\": Google Advertising ID is user-resettable ID unique for each device for advertising, provided by Google Play services.",
                        advertising_id));
        put(String.format("UIDType.%s", telephony_device_id),
                String.format("\"%s\": Telephony device ID is a category of unique device IDs, including the IMEI for GSM phones, and the MEID or ESN for CDMA phones",
                        telephony_device_id));
        put(String.format("UIDType.%s", line1_phone_number),
                String.format("\"%s\": The phone number", line1_phone_number));
        put(String.format("UIDType.%s", instance_id),
                String.format("\"%s\": Instance ID is an app-specific unique ID that is persistent for each install of your apps, and will be reset when the app is reinstalled, provided by Google Play services.",
                        instance_id));
        put(String.format("UIDType.%s", self_generated_uid),
                String.format("\"%s\": Self generated UID refers to the unique ID generated by your app. UUID.randomUUID() will return different values on each call, so it needs to be stored manually.",
                        self_generated_uid));
        put(String.format("UIDType.%s", mac_address),
                String.format("\"%s\": MAC address is a category of unique device IDs, including Wi-Fi MAC address and Bluetooth MAC address.",
                        mac_address));
        put(String.format("UIDScope.%s", per_app_scope),
                String.format("\"%s\": The unique ID is only used in this app.",
                        per_app_scope));
        put(String.format("UIDScope.%s", per_app_group_scope),
                String.format("\"%s\": The unique ID is shared across a group of apps.",
                        per_app_group_scope));
        put(String.format("%s", per_device_scope),
                String.format("\"%s\": The unique ID is shared across all apps on the device.",
                        per_device_scope));
        put(String.format("%s", user_resettable_in_system_settings),
                String.format("\"%s\": The user can reset the identifier in the system settings at anytime to avoid being tracked.",
                        user_resettable_in_system_settings));
        put(String.format("UIDResettability.%s", reset_when_session_end),
                String.format("\"%s\": The lifecycle of the ID is only during each session of the app, and the ID will be reset after the app is killed",
                        reset_when_session_end));
        put(String.format("UIDResettability.%s", reset_when_reinstall),
                String.format("\"%s\": The UID will be different for every installation, so the user can avoid being tracked by reinstalling the app.",
                        reset_when_reinstall));
        put(String.format("UIDResettability.%s", reset_after_factory_reset),
                String.format("\"%s\": The UID will be reset after factory reset.",
                        reset_after_factory_reset));
        put(String.format("UIDResettability.%s", persist_after_factory_reset),
                String.format("\"%s\": The UID will persist after factory reset.",
                        persist_after_factory_reset));
        put(String.format("LocationPurpose.%s", purpose_location_search_nearby_places),
                String.format("\"%s\": Use the current location to automatically search nearby places",
                        purpose_location_search_nearby_places));
        put(String.format("LocationPurpose.%s", purpose_provide_location_based_content),
                String.format("\"%s\": Provide customized service based on the user's current location.",
                        purpose_provide_location_based_content));
        put(String.format("LocationPurpose.%s", purpose_location_transportation_information),
                String.format("\"%s\": Provide users with local transportation information",
                        purpose_location_transportation_information));
        put(String.format("LocationPurpose.%s", purpose_location_recording),
                String.format("\"%s\": Recording user's location",
                        purpose_location_recording));
        put(String.format("LocationPurpose.%s", purpose_location_map_and_navigation),
                String.format("\"%s\": Use the current location to provide map and navigation services",
                        purpose_location_map_and_navigation));
        put(String.format("LocationPurpose.%s", purpose_location_geosocial_networking),
                String.format("\"%s\": Use the current location for networking activities with nearby people",
                        purpose_location_geosocial_networking));
        put(String.format("LocationPurpose.%s", purpose_location_geotagging),
                String.format("\"%s\": Use the current location to provide geotag for the content (e.g. photo)",
                        purpose_location_geotagging));
        put(String.format("LocationPurpose.%s", purpose_location_spoofing),
                String.format("\"%s\": Fake the current location",
                        purpose_location_spoofing)); // ? Does this purpose require the use of any API that can return location data?
        put(String.format("LocationPurpose.%s", purpose_location_alert_and_remind),
                String.format("\"%s\": Remind or send alert to the user when the current location meet certain conditions",
                        purpose_location_alert_and_remind));
        put(String.format("LocationPurpose.%s", purpose_location_location_based_game),
                String.format("\"%s\": Game based on current location",
                        purpose_location_location_based_game));
        put(String.format("LocationPurpose.%s", purpose_location_data_collection_for_analytics),
                String.format("\"%s\": Collecting user's location data for analytics",
                        purpose_location_data_collection_for_analytics));
        put(String.format("LocationPurpose.%s", purpose_location_data_collection_for_advertising),
                String.format("\"%s\": Collecting user's location data for providing personalized advertisement",
                        purpose_location_data_collection_for_advertising));
        put(String.format("UIDPurpose.%s", purpose_uid_tracking_user_data_collected_within_this_app),
                String.format("\"%s\": Track signed out anonymous users' information in this app. User data will be stored with this ID.",
                        purpose_uid_tracking_user_data_collected_within_this_app));
        put(String.format("UIDPurpose.%s", purpose_uid_tracking_user_data_collected_from_multiple_apps_on_this_device),
                String.format("\"%s\": Track signed out anonymous users' information in multiple apps. User data will be stored with this ID.",
                        purpose_uid_tracking_user_data_collected_from_multiple_apps_on_this_device));
        put(String.format("UIDPurpose.%s", purpose_uid_handle_multiple_installations),
                String.format("\"%s\": This ID is used to identify the correct instance of the app when it's installed on multiple devices for the same user. The ID is supposed to be unique, but not necessarily shared by other apps.",
                        purpose_uid_handle_multiple_installations));
        put(String.format("UIDPurpose.%s", purpose_uid_enforcing_free_content_limits),
                String.format("\"%s\": This ID is used to limit the number of free content (e.g. articles) a user can see on a device. The ID is supposed to be unique, but not necessarily shared by other apps.",
                        purpose_uid_enforcing_free_content_limits));
        put(String.format("UIDPurpose.%s", purpose_uid_managing_telephony_and_carrier_functionality),
                String.format("\"%s\": The ID is used for interacting with the device's phone and texting functionality, so corresponding telephony Device ID may be proper to use.",
                        purpose_uid_managing_telephony_and_carrier_functionality));
        put(String.format("UIDPurpose.%s", purpose_uid_identifying_bots_and_DDOS_attacks),
                String.format("\"%s\": This ID is used to detect multiple fake devices attacking your backend services.",
                        purpose_uid_identifying_bots_and_DDOS_attacks));
        put(String.format("UIDPurpose.%s", purpose_uid_detecting_high_value_stolen_credentials),
                String.format("\"%s\": This ID is used to detect if a single device is being used multiple times with high-value, stolen credentials (e.g. to make fraudulent payments).",
                        purpose_uid_detecting_high_value_stolen_credentials));
        put("visibility", "\"visibility\": Is the data used when the app is in background (BACKGROUND) or in foreground (WHILE_IN_USE)?");
        put("purpose", "\"purpose\": What's the purpose of using this data? What feature of the app requires this data? Select from a list of possible categories of purposes.");
        put("purposeDescription", "\"purposeDescription\": What's the purpose of collecting/sharing this data? What feature of the app requires this data? Provide the free-form description of the purpose.");
        put("frequency", "\"frequency\": When will this data collection behavior happen?");
        put("accessControl", "\"accessControl\": Is the stored data only accessible to this app, or shared by other apps?");
        put("retentionTime", "\"retentionTime\": How long is this data going to be retained locally or on remote servers?");
        put("isLocationDataEnabledInAppSettings", "\"isLocationDataEnabledInAppSettings\": (Boolean value expected here.) Location data is used for personalized advertising by default if the location permission is granted. It can only be turned off in the settings of your app on the app dashboard on google sites. (If you want to learn more, check out more detailed instruction: https://support.google.com/admob/answer/6373176?hl=en)");
        put("encryptedInTransmission", "\"encryptedInTransmission\": Is the data encrypted during transmission?");
        put("destination", "\"destination\": What's the destination of this network traffic?");
        put("scope", "\"scope\": Is this unique identifier unique to your app or also shared by other apps?");
        put("resettability", "\"resettability\": How can this unique identifier be reset?");
    }});

    public static final String ANNOTATION_REQUIRED = "%s annotation is required.";
    public static final String DEFINE_VARIABLE = "Please declare a variable to hold this value for adding privacy annotation (auto quickfixes provided)";
    public static final String INVALID_ANNOTATION = "The corresponding data source doesn't have a valid annotation.";
    public static final String INCONSISTENT_ANNOTATION = "The annotation is inconsistent with the speculation from the code (The annotation could be out-of-date).";
    public static final String CONFLICT_ANNOTATION = "The @NotPersonalData annotation is in conflict with other personal data annotations";
    public static final String MISSING_PERSONAL_DATA_ANNOTATION = "If the personal data is stored or transmitted out of the phone here, the corresponding personal data annotations are required, otherwise, the @NotPersonalData annotation is required.";

    public static final String fine_grained_latitude_longitude = "FINE_GRAINED_LATITUDE_LONGITUDE";
    public static final String coarse_grained_latitude_longitude = "COARSE_GRAINED_LATITUDE_LONGITUDE";
    public static final String city_level_latitude_longitude = "CITY_LEVEL_LATITUDE_LONGITUDE";
    public static final String block_level_latitude_longitude = "BLOCK_LEVEL_LATITUDE_LONGITUDE";

    public static final String acceleration = "ACCELERATION";
    public static final String custom_sensor_data = "CUSTOM_SENSOR_DATA";
    public static final String distance = "DISTANCE";
    public static final String gravity = "GRAVITY";
    public static final String heart_beat = "HEART_BEAT";
    public static final String heart_rate = "HEART_RATE";
    public static final String humidity = "HUMIDITY";
    public static final String light = "LIGHT";
    public static final String low_latency_offbody_detect = "LOW_LATENCY_OFFBODY_DETECT";
    public static final String magnetic_field_strength = "MAGNETIC_FIELD_STRENGTH";
    public static final String motion = "MOTION";
    public static final String number_of_steps = "NUMBER_OF_STEPS";
    public static final String pressure = "PRESSURE";
    public static final String proximity = "PROXIMITY";
    public static final String rotation = "ROTATION";
    public static final String temperature = "TEMPERATURE";

    public static final String image = "image";
    public static final String video = "video";
    public static final String metadata = "metadata";

    public static final String per_app_scope = "PER_APP";
    public static final String per_app_group_scope = "PER_APP_GROUP";
    public static final String per_device_scope = "PER_DEVICE";

    public static final String user_resettable_in_system_settings = "USER_RESETTABLE_IN_SYSTEM_SETTINGS";
    public static final String reset_when_session_end = "RESET_WHEN_SESSION_END";
    public static final String reset_when_reinstall = "RESET_WHEN_REINSTALL";
    public static final String reset_after_factory_reset = "RESET_WHEN_FACTORY_RESET";
    public static final String persist_after_factory_reset = "PERSIST_AFTER_FACTORY_RESET";

    public static final String advertising_id = "ADVERTISING_ID";
    public static final String telephony_device_id = "TELEPHONY_DEVICE_ID";
    public static final String line1_phone_number = "LINE1_PHONE_NUMBER";
    public static final String instance_id = "INSTANCE_ID";
    public static final String self_generated_uid = "SELF_GENERATED_UID";
    public static final String android_id = "ANDROID_ID";
    public static final String mac_address = "MAC_ADDRESS";

    public static final String advertising_id_description = "ADVERTISING_ID (google advertising ID, use getId() to acquire the advertising ID, and use isLimitAdTrackingEnabled() to get user's tracking preference)";
    public static final String telephony_device_id_description = "TELEPHONY_DEVICE_ID (IMEI, IMSI, MEID)";
    public static final String line1_phone_number_description = "LINE1_PHONE_NUMBER (the phone number)";
    public static final String instance_id_description = "INSTANCE_ID (google instance ID, app-specificUID, will be reset when the app is reinstalled)";
    public static final String self_generated_uid_description = "SELF_GENERATED_UID (using the UUID.randomUUID().toString() API to generate the UID. UUID.randomUUID() will return different values for different invocations, please store the UID manually.)";
    public static final String safetynet_description = "An identifier in isolation does little to indicate that a device is genuine. You can verify that a request comes from a genuine Android device (as opposed to an emulator or other code spoofing another device) using the Safetynet API's SafetyNet.SafetyNetApi.attest(mGoogleApiClient, nonce) method to verify the integrity of a device making a request. For more detailed information, please see Safetynet's API documentation";

    public static final String purpose_location_search_nearby_places = "search_nearby_places";
    public static final String purpose_provide_location_based_content = "provide_location_based_content";
    public static final String purpose_location_transportation_information = "transportation_information";
    public static final String purpose_location_recording = "recording";
    public static final String purpose_location_map_and_navigation = "map_and_navigation";
    public static final String purpose_location_geosocial_networking = "geosocial_networking";
    public static final String purpose_location_geotagging = "geotagging";
    public static final String purpose_location_spoofing = "spoofing";
    public static final String purpose_location_alert_and_remind = "alert_and_remind";
    public static final String purpose_location_location_based_game = "location_based_game";
    public static final String purpose_location_data_collection_for_analytics = "data_collection_for_analytics";
    public static final String purpose_location_data_collection_for_advertising = "data_collection_for_advertising";
    public static final String purpose_uid_tracking_user_data_collected_within_this_app = "tracking_user_data_collected_within_this_app";
    public static final String purpose_uid_tracking_user_data_collected_from_multiple_apps_on_this_device = "tracking_user_data_collected_from_multiple_apps_on_this_device";
    public static final String purpose_uid_handle_multiple_installations = "handle_multiple_installations";
    public static final String purpose_uid_enforcing_free_content_limits = "enforcing_free_content_limits";
    public static final String purpose_uid_managing_telephony_and_carrier_functionality = "managing_telephony_and_carrier_functionality";
    public static final String purpose_uid_identifying_bots_and_DDOS_attacks = "identifying_bots_and_DDOS_attacks";
    public static final String purpose_uid_detecting_high_value_stolen_credentials = "detecting_high_value_stolen_credentials";

    public static final String accessible_to_other_apps = "ACCESSIBLE_TO_OTHER_APPS";
    public static final String private_to_this_app = "PRIVATE_ACCESS";

    public static final String unique_id_type_privacy_warning_message_pattern = "We recommend to use the following unique identifiers that have more appropriate access scope and resettability for the purpose you specified instead (Quick-fixes provided): %s.";
    public static final String unique_id_resettability_privacy_warning_message_pattern = "The more appropriate resettability of the unique identifier for the purpose \"%s\" are %s.";
    public static final String unique_id_scope_privacy_warning_message_pattern = "The more appropriate scopes of the unique identifier for the purpose \"%s\" are %s)";
}
